const source = {
  ctrip: "携程新疆景点热度/评分",
  tripadvisor: "Tripadvisor 旅行者排名/评分",
  official: "新疆文旅/政务景区名录",
  guide: "热门自驾攻略与本地 Word 路书",
};

export const attractions = [
  spot("urumqi", "乌鲁木齐", "乌鲁木齐", "culture", "城市枢纽", 43.8256, 87.6168, "0.5-1天", 8.2, source.guide, "新疆自驾最常用的落地、租车和补给起点。"),
  spot("xinjiang-museum", "新疆维吾尔自治区博物馆", "乌鲁木齐", "culture", "博物馆", 43.8179, 87.5887, "2-3小时", 8.8, source.tripadvisor, "Tripadvisor 新疆旅行者排名前列，适合作为乌鲁木齐人文第一站。"),
  spot("bazaar", "新疆国际大巴扎", "乌鲁木齐", "culture", "市集街区", 43.7793, 87.6171, "2-4小时", 8.5, source.official, "乌鲁木齐 4A 景区，适合晚间体验美食、市集和城市烟火气。"),
  spot("urumqi-grand-canyon", "乌鲁木齐天山大峡谷", "乌鲁木齐", "nature", "峡谷雪山", 43.4459, 87.4702, "4-6小时", 8.7, source.official, "乌鲁木齐 5A 景区，适合不远行时看雪山、森林和峡谷。"),
  spot("tianchi", "天山天池", "昌吉", "nature", "湖泊雪山", 43.8844, 88.1333, "4-6小时", 9.3, source.ctrip, "携程必打卡榜高位，博格达峰下的高山湖泊。"),
  spot("jiangbulake", "江布拉克", "昌吉", "nature", "麦田草原", 43.9077, 89.7298, "0.5-1天", 9.1, source.ctrip, "携程显示 5A、约 4.7/5，好评高，适合东线自驾。"),
  spot("koktokay", "可可托海", "阿勒泰", "nature", "峡谷地质", 47.2059, 89.8551, "0.5-1天", 8.9, source.guide, "额尔齐斯河峡谷、花岗岩峰林和矿业遗迹构成北疆经典第一站。"),
  spot("burqin", "布尔津", "阿勒泰", "culture", "中转城镇", 47.7045, 86.8754, "过夜", 7.8, source.guide, "前往喀纳斯、禾木前的重要住宿和补给点。"),
  spot("kanas", "喀纳斯", "阿勒泰", "nature", "湖泊森林", 48.7495, 87.0396, "1-2天", 9.5, source.ctrip, "北疆代表性湖泊景区，晨雾、三湾、图瓦村落是核心体验。"),
  spot("hemu", "禾木", "阿勒泰", "nature", "村落森林", 48.5791, 87.4304, "1天", 9.2, source.ctrip, "木屋、白桦林和晨雾让这里成为阿勒泰环线高光停留点。"),
  spot("devil-city", "世界魔鬼城", "克拉玛依", "nature", "雅丹地貌", 46.1821, 85.7835, "2-4小时", 8.7, source.ctrip, "5A 雅丹地貌，适合在北疆西行途中安排日落时段。"),
  spot("sayram", "赛里木湖", "博州", "nature", "高山湖泊", 44.5946, 81.1744, "0.5-1天", 9.6, source.ctrip, "携程热度榜头部，环湖自驾体验成熟，湖泊、雪山、草地同框。"),
  spot("guozigou", "果子沟大桥", "伊犁", "nature", "公路景观", 44.4514, 80.8848, "1小时", 8.4, source.guide, "赛里木湖至伊宁方向的重要公路景观点。"),
  spot("yining", "伊宁", "伊犁", "culture", "城市人文", 43.9771, 81.518, "0.5-1天", 8.3, source.guide, "六星街、喀赞其等街区适合体验伊犁城市生活。"),
  spot("horgos", "霍尔果斯", "伊犁", "culture", "口岸", 44.2186, 80.4147, "2-4小时", 7.8, source.guide, "伊犁西线常见口岸打卡点，可与赛里木湖串联。"),
  spot("zhaosu", "昭苏", "伊犁", "nature", "草原花海", 43.1578, 81.1307, "0.5-1天", 8.5, source.guide, "夏季油菜花、草原和天马文化是伊犁环线亮点。"),
  spot("tekes", "特克斯八卦城", "伊犁", "culture", "城市格局", 43.2145, 81.8358, "半天", 8.4, source.guide, "无红绿灯的八卦形城市，是伊犁环线的特色住宿点。"),
  spot("kalajun", "喀拉峻草原", "伊犁", "nature", "草原峡谷", 43.0737, 82.0066, "1天", 9.0, source.guide, "草原、阔克苏峡谷和人体草原构成完整的一日游线路。"),
  spot("nalati", "那拉提草原", "伊犁", "nature", "草原雪山", 43.323, 84.0324, "1-2天", 9.2, source.ctrip, "携程北疆必打卡榜高位，空中草原、河谷草原、盘龙谷适合深度游。"),
  spot("bayinbuluk", "巴音布鲁克", "巴州", "nature", "草原湿地", 43.0301, 84.1516, "半天-1天", 8.9, source.official, "5A 景区，九曲十八弯日落是独库公路中段常见高光。"),
  spot("bosten", "博斯腾湖", "巴州", "nature", "湖泊湿地", 41.9822, 86.7547, "0.5-1天", 8.8, source.official, "巴州 5A 景区，中国大型内陆淡水湖，适合南疆环线湖泊支线。"),
  spot("lopnur", "罗布人村寨", "巴州", "culture", "民俗沙漠", 40.8634, 86.8547, "3-5小时", 8.2, source.official, "巴州 4A 景区，可体验罗布人文化、塔里木河与沙漠风光。"),
  spot("tarim-poplar", "塔里木胡杨林公园", "巴州", "nature", "胡杨林", 41.1724, 84.2537, "0.5-1天", 8.8, source.official, "轮台附近胡杨主题核心景区，秋季金色胡杨尤其适合自驾摄影。"),
  spot("duku-north", "独库公路北段", "伊犁/塔城", "nature", "景观公路", 43.9178, 84.8737, "半天", 9.0, source.guide, "独山子至乔尔玛方向，山路弯多，需关注季节开放和天气。"),
  spot("dushanzi-canyon", "独山子大峡谷", "克拉玛依", "nature", "峡谷", 44.1256, 84.7662, "2-3小时", 8.5, source.guide, "伊犁路书中的第一站，峡谷地貌和玻璃桥项目集中。"),
  spot("s101-anjihai", "安集海大峡谷", "塔城", "nature", "峡谷公路", 44.3281, 85.6188, "2小时", 8.4, source.guide, "S101 沿线视觉冲击强，适合从奎屯返回乌鲁木齐途中安排。"),
  spot("turpan", "吐鲁番", "吐鲁番", "culture", "历史葡萄沟", 42.9513, 89.1895, "0.5-1天", 8.4, source.guide, "葡萄沟、火焰山、坎儿井等可作为乌鲁木齐周边延伸。"),
  spot("kumtag", "库木塔格沙漠", "吐鲁番", "nature", "沙漠", 42.8694, 90.2136, "3-5小时", 9.0, source.ctrip, "携程约 4.7/5，鄯善城市边缘的流动沙漠，亲子和日落体验都强。"),
  spot("jiaohe", "交河故城", "吐鲁番", "culture", "古城遗址", 42.9478, 89.0672, "2-3小时", 8.7, source.tripadvisor, "Tripadvisor 新疆旅行者排名前列，吐鲁番历史遗址核心。"),
  spot("korla", "库尔勒", "巴州", "culture", "南疆枢纽", 41.7259, 86.1746, "过夜", 7.8, source.guide, "南疆环线进入塔里木盆地前后的常用中转城市。"),
  spot("kuqa", "库车", "阿克苏", "culture", "龟兹文化", 41.7179, 82.962, "1天", 8.6, source.guide, "连接独库南段、天山神秘大峡谷和龟兹文化遗迹。"),
  spot("kizil-caves", "克孜尔千佛洞", "阿克苏", "culture", "石窟壁画", 41.783, 82.5083, "2-3小时", 8.6, source.ctrip, "龟兹文化代表性石窟，可与库车王府、库车峡谷串联。"),
  spot("aksu", "阿克苏", "阿克苏", "culture", "城市人文", 41.1688, 80.2606, "半天-1天", 7.9, source.guide, "南疆路书提到老街夜市、温宿方向峡谷和周边古迹。"),
  spot("wensu-canyon", "温宿天山托木尔大峡谷", "阿克苏", "nature", "峡谷地貌", 41.7519, 80.7386, "4-6小时", 8.7, source.guide, "红色峡谷、五彩山和盐谷观景点密集，适合阿克苏周边一日游。"),
  spot("bachu-red-sea", "巴楚红海景区", "喀什", "nature", "胡杨湿地", 39.8117, 78.5505, "3-5小时", 8.2, source.guide, "南疆路书重点描述的胡杨、湿地、民俗和沙漠体验综合景区。"),
  spot("atush-arch", "阿图什天门", "克州", "nature", "天然石拱", 39.7161, 76.1836, "3-5小时", 8.3, source.guide, "南疆路书提到的天然石拱门与峡谷地貌，高山索道已成为新看点。"),
  spot("kashgar", "喀什古城", "喀什", "culture", "古城人文", 39.4704, 75.9898, "1天", 9.2, source.tripadvisor, "南疆人文核心，古城、巴扎、老茶馆和民居街巷集中。"),
  spot("livestock-market", "喀什牲畜巴扎", "喀什", "culture", "市集民俗", 39.5468, 76.0969, "2-3小时", 8.7, source.tripadvisor, "Tripadvisor 喀什热门景点前列，周末市集更有生活质感。"),
  spot("apakh-hoja", "香妃园", "喀什", "culture", "历史建筑", 39.4895, 76.038, "2小时", 8.4, source.tripadvisor, "喀什经典历史人文景区，可与古城同日安排。"),
  spot("baisha", "白沙湖", "克州", "nature", "高原湖泊", 38.3407, 75.0668, "1-2小时", 8.9, source.guide, "喀什至塔县途中标志性湖景，天气好时雪山倒影很出片。"),
  spot("karakul", "喀拉库勒湖", "克州", "nature", "高原湖泊", 38.435, 75.047, "1小时", 8.8, source.tripadvisor, "慕士塔格峰脚下的高原湖泊，Tripadvisor 新疆排名靠前。"),
  spot("muztagh", "慕士塔格冰川公园", "克州", "nature", "冰川雪山", 38.2785, 75.1097, "3-5小时", 8.6, source.guide, "高海拔冰川体验点，需注意天气、海拔和体力。"),
  spot("muji-volcano", "木吉火山口", "克州", "nature", "火山湿地", 39.247, 75.327, "2小时", 8.4, source.guide, "南疆路书称为帕米尔之眼，天气好时雪山、湿地、火山口层次丰富。"),
  spot("tashkurgan", "塔什库尔干", "喀什", "culture", "高原县城", 37.7754, 75.2299, "过夜", 8.2, source.guide, "帕米尔高原自驾住宿点，可串联盘龙古道、班迪尔蓝湖。"),
  spot("panlong", "盘龙古道", "喀什", "nature", "盘山公路", 37.6794, 75.2865, "2-3小时", 8.9, source.guide, "弯道密集的高原公路，适合从塔县周边环线体验。"),
  spot("bandier", "班迪尔蓝湖", "喀什", "nature", "高原湖泊", 37.7705, 75.4026, "1小时", 8.5, source.guide, "湖色随天气变化，常与盘龙古道同日串联。"),
  spot("hongqilafu", "红其拉甫", "喀什", "culture", "国门公路", 36.8497, 75.4306, "半天", 8.1, source.tripadvisor, "中巴友谊公路高海拔终点方向，出行前需确认通行政策。"),
  spot("hotan", "和田团城老街", "和田", "culture", "老街人文", 37.1121, 79.9236, "半天", 8.2, source.guide, "南疆路书中的终点文化精华，可看民居、地毯作坊和老茶馆。"),
  spot("shache", "莎车", "喀什", "culture", "王宫古城", 38.4145, 77.2458, "半天", 8.2, source.guide, "叶尔羌汗王宫建筑群和南疆古城文化节点。"),
  spot("alal", "阿拉尔", "兵团第一师", "culture", "军垦沙漠", 40.5419, 81.2807, "半天-1天", 8.0, source.guide, "三五九旅文化、沙漠之门、睡胡杨谷和塔里木河大桥可组合游览。"),
  spot("taklamakan", "塔克拉玛干沙漠公路", "塔里木盆地", "nature", "沙漠公路", 39.249, 83.675, "穿越", 8.7, source.guide, "南疆大环线的沙漠穿越体验，需提前规划油量和补给。"),
];

export const presetRoutes = [
  route("north-loop", "北疆自然大环线", "10-15天", "湖泊、森林、草原、独库公路", "#138a4f", [
    "urumqi",
    "xinjiang-museum",
    "tianchi",
    "koktokay",
    "burqin",
    "kanas",
    "hemu",
    "devil-city",
    "sayram",
    "nalati",
    "bayinbuluk",
    "duku-north",
    "dushanzi-canyon",
    "s101-anjihai",
    "urumqi",
  ]),
  route("ili-loop", "伊犁环线 10 日参考", "8-11天", "草原、峡谷、赛里木湖、S101", "#2f6fba", [
    "urumqi",
    "dushanzi-canyon",
    "duku-north",
    "nalati",
    "tekes",
    "kalajun",
    "zhaosu",
    "yining",
    "horgos",
    "sayram",
    "s101-anjihai",
    "turpan",
    "jiaohe",
    "urumqi",
  ]),
  route("south-loop", "南疆人文与帕米尔环线", "10-15天", "古城、沙漠、公路、高原湖泊", "#b7791f", [
    "urumqi",
    "korla",
    "bosten",
    "lopnur",
    "tarim-poplar",
    "kuqa",
    "kizil-caves",
    "aksu",
    "wensu-canyon",
    "bachu-red-sea",
    "atush-arch",
    "kashgar",
    "livestock-market",
    "apakh-hoja",
    "baisha",
    "karakul",
    "muji-volcano",
    "tashkurgan",
    "panlong",
    "bandier",
    "shache",
    "hotan",
    "taklamakan",
    "alal",
    "urumqi",
  ]),
  route("east-extension", "东疆吐鲁番与江布拉克支线", "3-5天", "博物馆、天池、麦田、沙漠、古城", "#6b5b95", [
    "urumqi",
    "bazaar",
    "urumqi-grand-canyon",
    "tianchi",
    "jiangbulake",
    "turpan",
    "jiaohe",
    "kumtag",
    "urumqi",
  ]),
];

export const sourceNotes = [
  "本地参考：南疆自驾路书.docx、伊犁环线自驾攻略-3.docx。",
  "线上参考：携程新疆景点热度/评分、Tripadvisor 旅行者排名、新疆文旅与政务景区名录、热门自驾攻略。",
  "0-10 分为综合推荐分：平台评分折算、评价数量/热度、景区等级、自驾路线价值共同加权。",
  "页面内置距离为未调用 Google 路线服务时的估算值；配置 Google Maps API key 后以 Google DirectionsService 返回为准。",
];

function spot(id, name, region, category, type, lat, lng, stay, score, ratingBasis, summary) {
  return {
    id,
    name,
    region,
    category,
    type,
    lat,
    lng,
    stay,
    score,
    ratingBasis,
    summary,
  };
}

function route(id, name, days, theme, color, stopIds) {
  return { id, name, days, theme, color, stopIds };
}
